import type { ContentBlock, ArticleStat } from "@/app/insights/[category]/[slug]/content";

export interface SiloArticle {
  slug: string;
  title: string;
  description: string;
  readTime: string;
  date: string;
  stats: ArticleStat[];
  blocks: ContentBlock[];
  faqs: { question: string; answer: string }[];
  related: string[];
}

export const SILO_META = {
  name: "AI SEO for Law Firms",
  description: "AI-first search optimization for law firms \u2014 covering generative engine optimization, entity SEO, structured data, and the signals that earn AI citations.",
  slug: "ai-seo",
};

export const ARTICLES: SiloArticle[] = [
  {
    slug: "ai-seo-for-law-firms",
    title: "AI SEO for Law Firms: The Complete Guide to AI-First Search Optimization",
    description: "Traditional SEO is no longer enough. Here is the complete guide to AI SEO \u2014 optimizing your law firm to be found and cited by ChatGPT, Gemini, and Perplexity.",
    readTime: "14 min read",
    date: "2026-06-18",
    stats: [
      { value: "40%", label: "of Google searches now show AI Overviews" },
      { value: "60%", label: "of all searches are zero-click" },
      { value: "3\u20135", label: "sources cited per AI-generated answer" },
    ],
    blocks: [
      { type: "h2", heading: "What Is AI SEO and Why Does It Matter for Law Firms?", text: "What Is AI SEO and Why Does It Matter for Law Firms?" },
      { type: "p", text: "AI SEO \u2014 also called Generative Engine Optimization or GEO \u2014 is the practice of optimizing your law firm's digital presence to appear in answers generated by AI platforms. Where traditional SEO aims to rank in Google's blue links, AI SEO aims to be cited inside the AI-generated summaries that now appear above those links, and inside the conversational answers that ChatGPT, Gemini, and Perplexity provide when users ask legal questions." },
      { type: "p", text: "The distinction matters because the AI layer is capturing more and more of users' attention. When 40% of Google searches show an AI Overview at the top of the page, the firms cited in those overviews receive visibility that the firms ranking below them in the blue links simply cannot match \u2014 and those users may never scroll down to the traditional results at all." },
      { type: "callout", text: "AI SEO does not replace traditional SEO \u2014 it extends it. The same foundations that earn Google rankings (authority, relevance, technical quality) also influence AI citations. The difference is in the additional signals that AI engines require: entity recognition, structured data, and question-and-answer content formats." },
      { type: "h2", heading: "The Four Pillars of AI SEO for Law Firms", text: "The Four Pillars of AI SEO for Law Firms" },
      { type: "ul", heading: "What AI SEO requires", items: ["Entity Authority: making sure AI engines know who your firm is, where you practice, and what you do.", "Content Depth: comprehensive, specific answers to the questions clients actually ask AI platforms.", "Structured Data: schema markup that makes your content machine-readable and citation-ready.", "Citation Signals: third-party mentions in trusted legal directories and publications."] },
      { type: "h2", heading: "Entity SEO: Making Your Firm Known to AI", text: "Entity SEO: Making Your Firm Known to AI" },
      { type: "p", text: "AI engines don't just index pages \u2014 they build knowledge graphs of entities: organizations, people, and places. Your law firm is an entity. The AI needs to know your firm's name, location, practice areas, attorneys, and how all these relate to each other. Entity signals come from consistent information across your website, Google Business Profile, legal directories, bar association listings, and any publication that mentions your firm." },
      { type: "h2", heading: "Content Strategy for AI Citation", text: "Content Strategy for AI Citation" },
      { type: "p", text: "AI-friendly content is specific, accurate, and structured. It answers a discrete question completely and correctly. A page titled 'Personal Injury Law' with three paragraphs of generic description will not earn AI citations. A page titled 'What to Do After a Car Accident in Texas: A Step-by-Step Guide' that answers the question thoroughly \u2014 with numbered steps, a FAQ section, and jurisdiction-specific accuracy \u2014 will." },
    ],
    faqs: [
      { question: "Is AI SEO only relevant for large law firms?", answer: "No. AI engines reward relevance and specificity, which small firms can achieve. A solo practitioner with highly specific, accurate answers about a narrow practice area in a specific jurisdiction can outperform a large generalist firm on AI citations for those queries." },
      { question: "How much does AI SEO differ from traditional SEO?", answer: "The foundations overlap significantly \u2014 authority, content quality, technical performance. AI SEO adds entity optimization and structured data as critical requirements, and places heavier weight on question-and-answer content formats that match how users interact with AI platforms." },
      { question: "How do I measure AI SEO performance?", answer: "Track: manual queries to ChatGPT, Perplexity, and Gemini for your target keywords; AI Overview appearances in Google Search Console; citation tracking through tools like Semrush AI Toolkit; and branded search growth as AI visibility drives awareness." },
    ],
    related: ["generative-engine-optimization-for-lawyers", "entity-seo-for-law-firms"],
  },
  {
    slug: "generative-engine-optimization-for-lawyers",
    title: "Generative Engine Optimization for Lawyers: What GEO Actually Means",
    description: "GEO \u2014 Generative Engine Optimization \u2014 is the emerging discipline of earning visibility inside AI-generated answers. Here is what it means for legal practices.",
    readTime: "11 min read",
    date: "2026-06-18",
    stats: [
      { value: "GEO", label: "the fastest-growing discipline in digital marketing" },
      { value: "2026", label: "the year GEO became essential for law firms" },
      { value: "10x", label: "potential reach increase for AI-cited content vs. page-5 rankings" },
    ],
    blocks: [
      { type: "h2", heading: "Defining Generative Engine Optimization", text: "Defining Generative Engine Optimization" },
      { type: "p", text: "Generative Engine Optimization is the practice of optimizing content and digital signals so that AI-powered 'generative engines' \u2014 platforms that create answers rather than returning lists of links \u2014 include your content in their responses. The term distinguishes the discipline from traditional SEO, which targets algorithmic ranking in link-based search results." },
      { type: "p", text: "For lawyers, the practical translation is this: when a potential client asks ChatGPT 'do I need a lawyer for a DUI in Colorado,' GEO is the set of practices that make it more likely that ChatGPT references your firm or your content in that answer. When they ask Perplexity 'what are my rights if I'm wrongfully terminated in California,' GEO determines whether your firm's content is one of the five citations shown." },
      { type: "callout", text: "The first generation of lawyers to master GEO will have a compounding advantage. AI citations build brand recognition, which drives direct searches, which builds more authority, which earns more citations. The loop is virtuous for those inside it \u2014 and painful for those outside." },
      { type: "h2", heading: "GEO Tactics That Work for Legal Practices", text: "GEO Tactics That Work for Legal Practices" },
      { type: "ul", heading: "High-impact GEO actions for law firms", items: ["Publish comprehensive FAQ pages structured around real AI queries for your practice area.", "Implement complete schema markup: LegalService, Attorney, FAQPage, BreadcrumbList.", "Build consistent entity profiles across Avvo, Martindale, FindLaw, and state bar directories.", "Create jurisdiction-specific content that AI platforms can accurately attribute to your location.", "Earn mentions in legal publications, local media, and trusted consumer sites.", "Structure content with clear H2/H3 headers that match common AI query patterns."] },
    ],
    faqs: [
      { question: "How is GEO different from SEO?", answer: "Traditional SEO targets algorithmic rankings in lists of links. GEO targets inclusion in AI-generated prose answers. The technical foundations overlap, but GEO places much greater emphasis on entity signals, structured data, and content formats that AI can parse and synthesize." },
      { question: "Do I need to hire a GEO specialist?", answer: "GEO is new enough that most 'specialists' are really SEO professionals who have extended their skills. Look for an agency that understands both traditional SEO fundamentals and the specific requirements of AI citation optimization." },
      { question: "Can I do GEO myself?", answer: "Yes, especially for content strategy and schema implementation. Adding FAQPage schema, building out Q&A content, and updating legal directories are tasks law firms can manage internally or with minimal outside help." },
    ],
    related: ["ai-seo-for-law-firms", "entity-seo-for-law-firms"],
  },
  {
    slug: "entity-seo-for-law-firms",
    title: "Entity SEO for Law Firms: How AI Engines Learn Who You Are",
    description: "AI engines reason about entities \u2014 organizations, people, places \u2014 not just pages. Here is how to build your firm as a recognized, trusted entity in AI knowledge graphs.",
    readTime: "10 min read",
    date: "2026-06-18",
    stats: [
      { value: "Entity", label: "signals now outweigh keyword density for AI ranking" },
      { value: "NAP", label: "consistency across 50+ directories is the baseline" },
      { value: "3x", label: "higher AI citation rate for firms with strong entity profiles" },
    ],
    blocks: [
      { type: "h2", heading: "What Is an Entity in AI Search?", text: "What Is an Entity in AI Search?" },
      { type: "p", text: "In AI search, an entity is a distinct, identifiable thing in the world \u2014 a person, organization, place, or concept. Your law firm is an entity. Each attorney at your firm is an entity. The practice areas you cover \u2014 personal injury, family law, criminal defense \u2014 are entities. AI engines build knowledge graphs that map how these entities relate to each other, and they use that graph to answer questions and make recommendations." },
      { type: "p", text: "For a law firm, entity SEO means ensuring that the AI's knowledge graph contains accurate, complete, and consistent information about your firm: your name, location, practice areas, attorneys, achievements, and connections to other trusted entities in the legal space. A firm with a rich, accurate entity profile can be confidently cited. A firm the AI barely recognizes cannot." },
      { type: "ul", heading: "Key entity signals for law firms", items: ["Consistent Name, Address, and Phone (NAP) across all online profiles.", "Google Business Profile with complete categories, services, and attributes.", "Avvo, Martindale-Hubbell, FindLaw, Justia, and state bar profiles \u2014 all consistent.", "Attorney Wikipedia pages or Wikidata entries for senior partners.", "sameAs links in your website schema connecting to authoritative profiles.", "Mentions in local media, legal publications, and industry awards."] },
      { type: "callout", text: "NAP inconsistency is one of the most damaging entity signals a law firm can send. If your firm appears as 'Smith & Jones, LLC' in one directory and 'Smith and Jones Law' in another, AI engines struggle to unify these as the same entity \u2014 which reduces citation confidence." },
    ],
    faqs: [
      { question: "What is the most important entity signal for a law firm?", answer: "Google Business Profile is the single most influential entity signal for local law firm visibility in AI search. Keep it complete, accurate, and actively managed \u2014 including responding to reviews and adding photos regularly." },
      { question: "How do I find all the places my firm appears online?", answer: "Use tools like Moz Local, BrightLocal, or Whitespark to audit your citation presence. Search your firm name in quotes on Google and review the first five pages of results to identify all active profiles." },
      { question: "Does Wikipedia matter for entity SEO?", answer: "Yes, especially for individual attorneys. Wikipedia and Wikidata pages create strong entity signals that AI knowledge graphs directly consume. However, Wikipedia has strict notability requirements \u2014 focus on qualifying through legitimate achievements before attempting a Wikipedia page." },
    ],
    related: ["ai-seo-for-law-firms", "generative-engine-optimization-for-lawyers"],
  },
];

export const ARTICLE_SLUGS = ARTICLES.map((a) => a.slug);
